version: '3'

services:
  autopaint:
    build:
      context: .
      dockerfile: ./watcher/Dockerfile
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    restart: unless-stopped
